---
title: B Major
timezone: UTC
collections:
  concerts:
    title: Concerts
    output: true
    permalink: /concerten/
    permalink_en: /concerts/
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  locations:
    title: locations
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: concerts
  values:
    layout: page
    image: ''
- scope:
    path: ''
    type: locations
  values:
    layout: page
    image: ''
permalink: pretty
navigation:
- title: about
  url: "/about"
exclude:
- _site
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- README.md
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
gems:
  - jekyll-multiple-languages-plugin
languages: ["nl", "en"]
exclude_from_localizations: ["scss", "css", "img", "js", "vendor", "uploads", "apple-touch-icon-precomposed.png", "favicon.ico", "favicon.png"]
