---
title: B Major
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  en_concerts:
    title: en_concerts
    output: true
    permalink: "/en/line-up/:path/"
  nl_concerts:
    title: nl_concerts
    output: true
    permalink: "/programma/:path/"
  nl_locations:
    title: nl_locations
    output: true
    permalink: "/locaties/:path/"
  nl_partners:
    title: nl_partners
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    section: ''
- scope:
    path: ''
    type: nl_concerts
  values:
    nl_location: ''
    nl_partner: ''
    lang: nl
    image: ''
    section: line-up
    layout: concert
    price: ''
    ticket URL: ''
    starts_at: ''
    ends_at: ''
- scope:
    path: ''
    type: en_concerts
  values:
    en_location: ''
    en_partner: ''
    lang: en
    image: ''
    section: line-up
    layout: concert
    price: ''
    ticket URL: ''
    starts_at: ''
    ends_at: ''
- scope:
    path: ''
    type: nl_locations
  values:
    layout: page
    image: ''
    section: locations
    lang: nl
permalink: pretty
navigation:
- section: about
  title: over
  title_en: about
  url: "/over"
  url_en: "/en/about"
- section: line-up
  title: programma
  title_en: line-up
  url: "/programma"
  url_en: "/en/line-up"
- section: locations
  title: locaties
  title_en: locations
  url: "/locaties"
  url_en: "/en/locations"
exclude:
- _site
- scss
- Gemfile.lock
- "*scss"
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- README.md
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
