---
title: B Major
timezone: UTC
collections:
  concerts:
    title: Concerts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  locations:
    title: locations
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: concerts
  values:
    layout: page
    image: ''
permalink: pretty
navigation:
- title: about
  url: "/about"
exclude:
- _site
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- README.md
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
