---
title: B Major
timezone: UTC
# gems:
# - jekyll-multiple-languages-plugin
# languages:
# - nl
# - en
# exclude_from_localizations:
# - scss
# - css
# - img
# - js
# - vendor
# - uploads
# - apple-touch-icon-precomposed.png
# - favicon.ico
# - favicon.png
collections:
  nl_concerts:
    output: true
    permalink: /programma/:path/
  en_concerts:
    output: true
    permalink: /en/line-up/:path/
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  locations:
    title: locations
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    section: ''
- scope:
    path: ''
    type: nl_concerts
  values:
    location: ''
    lang: ''
    image: ''
    section: line-up
    layout: page
    prijs: ''
    partner: ''
    concert date: ''
- scope:
    path: ''
    type: en_concerts
  values:
    location: ''
    lang: ''
    image: ''
    section: line-up
    layout: page
    prijs: ''
    partner: ''
    concert date: ''
- scope:
    path: ''
    type: locations
  values:
    layout: page
    image: ''
permalink: pretty
navigation:
- section: about
  title: over
  title_en: about
  url: "/over"
  url_en: "/en/about"
- section: line-up
  title: programma
  title_en: line-up
  url: "/programma"
  url_en: "/en/line-up"
exclude:
- _site
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- README.md
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
